# Generated by Django 3.0 on 2019-12-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20191209_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
